version: '2'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./data/mysql_conf/:/etc/mysql/conf.d/
      - ./data/mysql_data:/var/lib/mysql
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: confluence
      MYSQL_USER: confluence
      MYSQL_PASSWORD: confluence123
  confluence:
    build: .
    ports:
      - "8096:8090"